apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/praiskup/norpm-testing-container?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: norpm
    appstudio.openshift.io/component: norpm-testing-image
    pipelines.appstudio.openshift.io/type: build
  name: norpm-testing-image-on-pull-request
  namespace: fedora-copr-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/fedora-copr-tenant/norpm-testing-image:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: /Containerfile
  - name: build-platforms
    value:
      - linux/x86_64
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/olm-operator-konflux-sample.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/multi-arch-build-pipeline.yaml
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
